### ISSUE TITLE
Method to pass a base64 string directly to veryfi, rather than a temp file

### ISSUE THREAD

**Issue by gurudewan** [veryfi/veryfi-python#1]
Could the veryfi client also accept base 64 images rather than a file path to one? I need to store my image in a temp file just so you can decode it back! Seems wasteful.

If it already exists, please excuse me and point me in the right direction :)

**Comment by manycoding** [comment]
If you look in `process_document` code, it's pretty straightforward:

`import requests

endpoint_name = "/documents/"
if not categories:
    categories = self.CATEGORIES
file_name = os.path.basename(file_path)
request_arguments = {"file_name": file_name,
                        "file_data": base64_encoded_string,
                        "categories": categories,
                        "auto_delete": delete_after_processing}
document = self._request('POST', endpoint_name, request_arguments)`

**Comment by gurudewan** [comment]
You're right - but I meant a method implemented within the python SDK itself (I appreciate it's a really minor issue and not at all urgent :)

**Comment by manycoding** [comment]
@gurudewan You are welcome to submit PR with this method.

**Comment by veryfi** [comment]
Thank you guys, I'm going to close this issue.
